sudo: required
services:
  - docker

before_install:
  - docker build -t razvantodea14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true razvantodea14/docker-react npm run test

deploy:
  provider: elesticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-393400446511"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY